all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
      ansible_host: 192.168.99.11
#192.168.99.10 ansible_user: vagrant ansible_password=vagrant 
#192.168.99.11 ansible_user=vagrant ansible_password=vagrant
